server:
  port: 8802

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id:  urm-service
          uri: lb://URM-SERVICE
          predicates:
            - Path=/**
          filters:
            - Auth

  redis:
    timeout: 6000ms
    password:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
        - 192.168.0.117:6379
        - 192.168.0.116:6379
        - 192.168.0.118:6379
        - 192.168.0.119:6379
        - 192.168.0.120:6379
        - 192.168.0.121:6379
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 20 # 连接池中的最小空闲连接
        max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）

  main:
    allow-bean-definition-overriding: true