mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

spring:
  cache:
    type: redis
  datasource:
    dynamic:
      hikari:
        max-pool-size: 50
        max-lifetime: 1800000
        connection-timeout: 30000
        min-idle: 5
        is-auto-commit: true
      primary: read
      datasource:
        write:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.0.116:6446/jk_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: jk
          password: 123jk
        read:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.0.116:6447/jk_test?useUnicode=true&characterEncoding=utf-8
          username: jk
          password: 123jk
  redis:
    timeout: 6000ms
    password:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
        - 192.168.0.117:6379
        - 192.168.0.116:6379
        - 192.168.0.118:6379
        - 192.168.0.119:6379
        - 192.168.0.120:6379
        - 192.168.0.121:6379
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 20 # 连接池中的最小空闲连接
        max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）




logging:
  level:
    com.jk.mysqlroad.mapper: debug
